"use client";

import { CheckCircle2, CloudRain, Droplets, LoaderCircle, Sprout, XCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Slider } from "@/components/ui/slider";
import type { CropValidation, SimulationInput } from "@/types";

const fieldStyle = "mt-2 w-full rounded-xl border border-earth-100 bg-earth-50 p-2.5 text-sm text-earth-900 outline-none focus:border-earth-500";
export function ControlPanel({ input, validation, validating, onChange, onValidateCrop }: { input: SimulationInput; validation: CropValidation | null; validating: boolean; onChange: (input: SimulationInput) => void; onValidateCrop: () => void }) {
  const validationIcon = validating ? <LoaderCircle className="animate-spin text-earth-700" size={16}/> : validation?.isCrop ? <CheckCircle2 className="text-emerald-600" size={16}/> : validation ? <XCircle className="text-red-600" size={16}/> : null;
  return <Card className="space-y-5"><div><h2 className="font-bold text-earth-900">Escenario de cultivo</h2><p className="text-sm text-slate-500">Ajusta las condiciones de tu parcela.</p></div><label className="block text-sm font-medium"><span className="flex items-center gap-2"><Sprout size={16}/> Cultivo</span><div className="relative"><input value={input.crop} onChange={event => onChange({ ...input, crop: event.target.value })} onBlur={onValidateCrop} placeholder="Ej. cacao, arroz o yuca" className={fieldStyle}/><span className="absolute right-3 top-5">{validationIcon}</span></div><p className={`mt-1 text-xs ${validation?.isCrop ? "text-emerald-700" : validation ? "text-red-700" : "text-slate-500"}`}>{validating ? "Validando cultivo con IA…" : validation ? validation.reason : "Escribe un cultivo y sal del campo para validarlo con IA."}</p></label><label className="block text-sm font-medium">Tipo de suelo<select value={input.soilType} onChange={event => onChange({ ...input, soilType: event.target.value })} className={fieldStyle}>{["Arcilloso", "Franco", "Arenoso"].map(value => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-medium"><span className="flex items-center gap-2"><CloudRain size={16}/> Lluvias</span><select value={input.rainfallScenario} onChange={event => onChange({ ...input, rainfallScenario: event.target.value })} className={fieldStyle}><option>Estación habitual</option><option>Déficit de lluvias</option><option>Lluvias intensas</option></select></label><div><div className="mb-3 flex items-center justify-between text-sm font-medium"><span className="flex items-center gap-2"><Droplets size={16}/> Cambio de riego</span><span className="text-earth-700">{input.irrigationChange > 0 ? "+" : ""}{input.irrigationChange}%</span></div><Slider value={[input.irrigationChange]} onValueChange={([irrigationChange]) => onChange({ ...input, irrigationChange })}/></div></Card>;
}
