"use client";
import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { Bot, ImagePlus, Maximize2, Minimize2, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { downloadDiagnosisPdf } from "@/lib/pdfReport";
import type { DiagnosisChatMessage, DiagnosisRecord } from "@/types";
const asDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
export function DiagnosisChat({ record, onUpdate, onClose }: { record: DiagnosisRecord; onUpdate: (messages: DiagnosisChatMessage[]) => void; onClose: () => void }) { const [messages, setMessages] = useState(record.messages); const [draft, setDraft] = useState(""); const [attachment, setAttachment] = useState<File | null>(null); const [attachmentUrl, setAttachmentUrl] = useState<string>(); const [loading, setLoading] = useState(false); const [minimized, setMinimized] = useState(false); const inputRef = useRef<HTMLInputElement>(null); const commit = (next: DiagnosisChatMessage[]) => { setMessages(next); onUpdate(next); }; const attach = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0] ?? null; if (!file) return; setAttachment(file); setAttachmentUrl(await asDataUrl(file)); };
async function send(event: FormEvent) { event.preventDefault(); const text = draft.trim(); if ((!text && !attachment) || loading) return; const userMessage: DiagnosisChatMessage = { role: "user", content: text || "Adjunto una nueva foto para seguimiento.", imageUrl: attachmentUrl }; const next = [...messages, userMessage]; commit(next); setDraft(""); setLoading(true); try { const form = new FormData(); form.append("diagnosis", JSON.stringify(record.diagnosis)); form.append("messages", JSON.stringify(next.map(({ role, content }) => ({ role, content })))); if (attachment) form.append("image", attachment); const response = await fetch("/api/diagnosis-chat", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); commit([...next, { role: "assistant", content: data.reply }]); } catch (error) { commit([...next, { role: "assistant", content: error instanceof Error ? error.message : "No fue posible responder." }]); } finally { setAttachment(null); setAttachmentUrl(undefined); setLoading(false); } }
function close() { if (window.confirm("¿Deseas guardar el reporte del diagnóstico en PDF antes de cerrar?")) downloadDiagnosisPdf({ ...record, messages }); onClose(); }
if (minimized) return <button onClick={() => setMinimized(false)} className="fixed bottom-5 right-5 z-[1000] flex items-center gap-2 rounded-full bg-earth-700 px-4 py-3 text-sm font-semibold text-white shadow-xl"><Maximize2 size={17}/> Abrir diagnóstico</button>;
return <div className="fixed inset-0 z-[1000] flex items-end justify-end bg-slate-950/20 p-4 sm:p-6"><section className="flex h-[min(700px,88vh)] w-full max-w-md flex-col overflow-hidden rounded-2xl border border-earth-100 bg-white shadow-2xl"><header className="flex items-start justify-between bg-earth-700 p-4 text-white"><div className="flex gap-2"><Bot size={20}/><div><h2 className="font-semibold">Asistente fitosanitario</h2><p className="text-xs text-earth-100">{record.diagnosis.cultivo_detectado} · {record.diagnosis.problema_principal}</p></div></div><div className="flex gap-3"><button aria-label="Minimizar" onClick={() => setMinimized(true)}><Minimize2 size={20}/></button><button aria-label="Cerrar" onClick={close}><X size={20}/></button></div></header><div className="flex-1 space-y-3 overflow-y-auto p-4"><div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{record.imageUrl && <img src={record.imageUrl} alt="Evidencia original" className="mb-2 max-h-36 w-full rounded-lg object-cover"/>}<strong>{record.diagnosis.severidad}:</strong> {record.diagnosis.resumen_analisis}{record.note && <p className="mt-2 border-t border-amber-200 pt-2"><strong>Nota original:</strong> {record.note}</p>}</div>{messages.map((message, index) => <div key={index} className={`max-w-[88%] ${message.role === "user" ? "ml-auto" : ""}`}>{message.imageUrl && <img src={message.imageUrl} alt="Evidencia adjunta" className="mb-1 max-h-36 rounded-xl object-cover"/>}<p className={`rounded-2xl px-3 py-2 text-sm ${message.role === "user" ? "bg-earth-700 text-white" : "bg-earth-50 text-slate-700"}`}>{message.content}</p></div>)}{loading && <p className="w-fit rounded-2xl bg-earth-50 px-3 py-2 text-sm text-slate-500">Analizando…</p>}</div><form onSubmit={send} className="border-t border-earth-100 p-3"><input ref={inputRef} className="hidden" type="file" accept="image/*" onChange={attach}/>{attachmentUrl && <img src={attachmentUrl} alt="Nueva evidencia" className="mb-2 h-16 rounded-lg object-cover"/>}<div className="flex gap-2"><input value={draft} onChange={event => setDraft(event.target.value)} placeholder="Pregunta o añade seguimiento…" className="min-w-0 flex-1 rounded-xl border border-earth-100 px-3 py-2 text-sm outline-none focus:border-earth-500"/><Button type="button" variant="outline" aria-label="Adjuntar imagen" className="px-3" onClick={() => inputRef.current?.click()}><ImagePlus size={17}/></Button><Button aria-label="Enviar mensaje" className="px-3" disabled={loading}><Send size={17}/></Button></div></form><p className="px-4 pb-3 text-[11px] text-slate-500">{record.diagnosis.advertencia_legal}</p></section></div>; }
