"use client";
import dynamic from "next/dynamic"; import { useEffect, useState } from "react"; import { History, MapPin, Play, RotateCcw } from "lucide-react";
import { Header } from "@/components/shared/Header"; import { Footer } from "@/components/shared/Footer"; import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card";
import { ControlPanel } from "@/components/simulation/ControlPanel"; import { CropAlternatives } from "@/components/simulation/CropAlternatives"; import { DiagnosisChat } from "@/components/simulation/DiagnosisChat"; import { InputMedia } from "@/components/simulation/InputMedia"; import { ResultsDashboard } from "@/components/simulation/ResultsDashboard";
import { validateParcelLand } from "@/lib/geography"; import { polygonAreaHa } from "@/lib/utils"; import type { AgroPlan, Coordinate, CropValidation, DiagnosisRecord, EvidenceDiagnosis, SimulationInput } from "@/types";
const MapCanvas = dynamic(() => import("@/components/map/MapContainer").then(module => module.MapCanvas), { ssr: false, loading: () => <div className="h-[410px] animate-pulse rounded-2xl bg-earth-100"/> });
const initial: SimulationInput = { crop: "Cacao", soilType: "Franco", irrigationChange: 0, rainfallScenario: "Estación habitual", parcel: null }; const historyKey = "agrosim-diagnosis-history";
const toDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
export default function Home() { const [input, setInput] = useState<SimulationInput>(initial), [result, setResult] = useState<AgroPlan | null>(null), [activeRecord, setActiveRecord] = useState<DiagnosisRecord | null>(null), [records, setRecords] = useState<DiagnosisRecord[]>([]), [historyLoaded, setHistoryLoaded] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(""), [validatingCrop, setValidatingCrop] = useState(false); const [cropValidation, setCropValidation] = useState<CropValidation | null>({ isCrop: true, normalizedCrop: "Cacao", reason: "Cultivo inicial validado." }); const land = input.parcel ? validateParcelLand(input.parcel.coordinates) : null; const zones = result?.geometria_parcelas_sugerida.subdivisiones ?? [];
useEffect(() => { try { setRecords(JSON.parse(localStorage.getItem(historyKey) ?? "[]")); } catch { setRecords([]); } finally { setHistoryLoaded(true); } }, []); useEffect(() => { if (historyLoaded) localStorage.setItem(historyKey, JSON.stringify(records)); }, [historyLoaded, records]); const updateRecord = (updated: DiagnosisRecord) => { setActiveRecord(updated); setRecords(previous => [updated, ...previous.filter(record => record.id !== updated.id)]); };
const updatePoints = (coordinates: Coordinate[]) => setInput(value => ({ ...value, parcel: { coordinates, areaHa: polygonAreaHa(coordinates) } })); const updateInput = (value: SimulationInput) => { setInput(value); setCropValidation(null); };
async function validateCrop() { const crop = input.crop.trim(); if (!crop) { setCropValidation({ isCrop: false, normalizedCrop: "", reason: "Ingresa el nombre de un cultivo." }); return; } setValidatingCrop(true); setCropValidation(null); try { const response = await fetch("/api/validate-crop", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ crop }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setCropValidation(data); if (data.isCrop) setInput(value => ({ ...value, crop: data.normalizedCrop })); } catch (caught) { setCropValidation({ isCrop: false, normalizedCrop: "", reason: caught instanceof Error ? caught.message : "No fue posible validar." }); } finally { setValidatingCrop(false); } }
async function simulate() { if (!cropValidation?.isCrop || !land?.isCultivable) { setError(land?.advice ?? "Valida el cultivo y parcela antes de simular."); return; } setLoading(true); setError(""); try { const response = await fetch("/api/simulate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error al simular."); } finally { setLoading(false); } }
async function diagnose(file: File | null, note: string) { setLoading(true); setError(""); try { const form = new FormData(); if (file) form.append("image", file); form.append("note", note); const response = await fetch("/api/diagnose", { method: "POST", body: form }); const diagnosis = await response.json() as EvidenceDiagnosis; if (!response.ok) throw new Error((diagnosis as unknown as { error: string }).error); const record: DiagnosisRecord = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), diagnosis, note, imageUrl: file ? await toDataUrl(file) : undefined, messages: [{ role: "assistant", content: `Identifiqué ${diagnosis.problema_principal} en ${diagnosis.cultivo_detectado}. Puedes preguntarme sobre manejo, prevención o señales a vigilar.` }] }; updateRecord(record); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error al diagnosticar."); } finally { setLoading(false); } }
return <><Header/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-7 max-w-3xl"><p className="mb-2 text-sm font-semibold uppercase tracking-widest text-earth-700">Manabí · Ecuador</p><h2 className="text-3xl font-bold tracking-tight text-earth-900 sm:text-4xl">Convierte tu parcela en decisiones más resilientes.</h2></div><div className="grid gap-5 lg:grid-cols-[350px_1fr]"><aside className="space-y-5"><ControlPanel input={input} validation={cropValidation} validating={validatingCrop} onChange={updateInput} onValidateCrop={validateCrop}/><InputMedia loading={loading} onDiagnose={diagnose}/><Card><h2 className="mb-3 flex items-center gap-2 font-bold text-earth-900"><History size={17}/> Diagnósticos guardados</h2><div className="max-h-52 space-y-2 overflow-y-auto">{records.length ? records.map(record => <button className="w-full rounded-xl border border-earth-100 p-2 text-left text-sm hover:bg-earth-50" onClick={() => setActiveRecord(record)} key={record.id}><strong>{record.diagnosis.cultivo_detectado} · {record.diagnosis.problema_principal}</strong><span className="mt-1 block text-xs text-slate-500">{new Date(record.createdAt).toLocaleDateString("es-EC")}</span></button>) : <p className="text-sm text-slate-500">Los diagnósticos que realices aparecerán aquí.</p>}</div></Card></aside><div className="space-y-5"><Card><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold text-earth-900"><MapPin size={18}/> Delimita tu parcela</h2><p className="text-sm text-slate-500">Haz clic en el mapa para añadir vértices.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { setInput(value => ({ ...value, parcel: null })); setResult(null); }}><RotateCcw size={16}/></Button><Button disabled={loading || validatingCrop || !cropValidation?.isCrop || !land?.isCultivable} onClick={simulate} className="gap-2"><Play size={16}/>{loading ? "Simulando…" : "Ejecutar simulación"}</Button></div></div><MapCanvas parcel={input.parcel} zones={zones} onChange={updatePoints}/>{land && <p className={`mt-3 rounded-xl p-3 text-sm ${land.isCultivable ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{land.advice}</p>}</Card>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<ResultsDashboard result={result} input={input}/>{result && <CropAlternatives zones={zones} input={input}/>}</div></div></main>{activeRecord && <DiagnosisChat record={activeRecord} onUpdate={messages => updateRecord({ ...activeRecord, messages })} onClose={() => setActiveRecord(null)}/>}<Footer/></>; }
